version: '3.8'
services:
  app:
    container_name: bds-dashboard
    build: .
    ports:
      - 19132:19132/udp
    restart: unless-stopped
    volumes:
      - ./plugins:/servers/plugins
      - ./worlds:/servers/worlds
